config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'bar_games/index'
  get 'bars/show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "bars#index"

  resources :games, only: [:show, :edit, :update, :new, :create, :index, :destroy]

  resources :bars, only: [:show, :index], on: :members do
    resources :bar_games, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :games, through: :bar_games
  has_many :bar_games
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :address, presence: true
end

app/models/bar_game.rb
class BarGame < ApplicationRecord
  belongs_to :bar
  belongs_to :game
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bar_game
  belongs_to :user

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :bars, through: :bar_games
  has_many :bar_games
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :Booking
  has_many :bar
  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bar_games_controller.rb
class BarGamesController < ApplicationController
  def index
    if params[:bar_id].present?
      @bargames = BarGame.where(bar_id: params[:bar_id])
    else
      @bargames = BarGame.all
    end
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

    before_action :set_bar, only: [:show]

  def show
  end

  def index
    @bars = Bar.all

    @markers = @bars.geocoded.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {bar: bar})
      }
    end
  end

  private

  def set_bar
    @bar = Bar.find(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :game_params, only: [:create]

  def index
    @games = Game.all
  end

  def show
  end

  def edit
  end

  def new
    @game = Game.new
  end

  def create
    if game_params[:barcode].present?
     @game = Games::Creator.new(game_params[:barcode]).call
    else
      @game = Game.new(game_params)
    end
    @game.name = 'Unknown Game Name' if @game.name.strip.blank?
    if @game.save!
      redirect_to @game
    else
      render "new"
    end
  end

  def update
    respond_to do |format|
      if @game.update!(
        description: game_params[:description].presence,
        name: game_params[:name].presence,
        image_link: game_params[:image_link].presence)

          format.html { redirect_to(@game,
          :notice => "Game description was successfully updated.") }
      end
    rescue ActiveRecord::NotNullViolation
      format.html { redirect_to(@game,
          :alert => "Game name was not updated."
      )
    }
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path, :notice => "Your game has been deleted 🎮"
  end

  private

  def game_params
    params.require(:game).permit(:name, :label, :description, :image_link, :barcode)
  end

  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bar_games/index.html.erb
<div class="back_btn">
  <%= link_to :back do %>
    <%= image_tag "back.png" %>
  <%end%>
</div>

<% @bargames.each do |bargame|%>
  <%= render "shared/game_show", game: bargame.game, bar: bargame.bar %>
<%end%>

app/views/bars/index.erb
<% @bars.each do |bar| %>
  <div class="card-product">
    <img src="https://www.toulouse-tourisme.com/assets/uploads/sites/3/2023/12/terrasse-restaurant-toulouse.jpg" alt="">
    <div class="card-product-infos">
      <h1><%= bar.name %></h1>
      <p>
        <%= bar.description %>
        <%= bar.address %>
        <%= bar.phone_number %>
        <%= bar.number_of_tables %>
        <%= bar.number_of_seats %>
      </p>

      <%= link_to 'View this bar', bar_path(bar)%>
    </div>
  </div>
<%end%>

app/views/bars/index.html.erb
<div
  style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<div class="container-cards">
  <% @bars.each do |bar| %>
    <div class="bar_btn"><%= link_to bar_path(bar) do%>

      <div class="card-product">
        <img src="https://www.toulouse-tourisme.com/assets/uploads/sites/3/2023/12/terrasse-restaurant-toulouse.jpg" alt="">

        <div class="card-product-infos">
          <h1><%= bar.name %></h1>
          <p>
            <%= bar.description %> <br> <br>
            <%= bar.address %> <br>
            <%= bar.phone_number %> <br>
            <%= bar.number_of_tables %> <br>
            <%= bar.number_of_seats %>
          </p>

        </div>
      </div>
    <%end%> </div>
  <%end%>
</div>

app/views/bars/show.html.erb
<div class="back_btn">
  <%= link_to bars_path do %>
    <%= image_tag "back.png" %>
  <%end%>
</div>

<div class="banner">
  <img src="https://www.toulouse-tourisme.com/assets/uploads/sites/3/2023/12/terrasse-restaurant-toulouse.jpg" alt="">
</div>

<h1 class="title_bar"><%= @bar.name %></h1>

<div class="container_bar">
  <div class="row">

    <div class="description col-6">
        <p>
          SPECIAL EVENT <br>
          🎲 Game pass <br>
          🍺 Happy hour
        </p>
    </div>

    <div class="description col-6">
      <%= @bar.description %>
    </div>

  </div>
</div>

<div class="container_bar">
  <div class="row">

    <div class="description col-6">
      <p>
        <%= @bar.address %> <br>
        <a href="tel:<%= @bar.phone_number %>", class="tel"><%= @bar.phone_number %></a> <br>
        <%= @bar.number_of_tables %> <br>
        <%= @bar.number_of_seats %>
      </p>
    </div>

    <div class="description col-6">
      <%= link_to 'View games', bar_bar_games_path(@bar), class:"btn"%>
    </div>

  </div>
</div>

app/views/games/edit.html.erb
<%= render 'shared/form'%>

app/views/games/index.erb
<div class="Add_game_btn">
  <%= link_to new_game_path do %>
    <%= image_tag "new_game.png" %>
  <%end%>
</div>

<% @games.each do |game|%>
  <div class="card-product">
    <% src = game.image_link ? game.image_link : "https://cf.geekdo-images.com/BZiR636JJdSBwThtH42DVw__opengraph/img/_Iu_09Ab0fvnTJT3gBCfud0LbJg=/0x0:800x420/fit-in/1200x630/filters:strip_icc()/pic3744052.jpg"%>
    <img src=<%= src %>>
    <div class="card-product-infos">

        <h1><%= game.name %></h1>
        <p>
          <%=game.label%>
          <%=game.description%>
        </p>
        <%= link_to 'More', game_path(game)%>
        <%= link_to 'Edit', edit_game_path(game)%>
    </div>
  </div>
<%end%>

app/views/games/new.html.erb
<%= render 'shared/form' %>

app/views/games/show.html.erb
<div class="back_btn">
  <%= link_to :back do %>
    <%= image_tag "back.png" %>
  <%end%>
</div>
<%= render "shared/game_show", game: @game, bar: @bar ? @bar : nil %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarAJeux</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v3.5.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v3.5.1/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <div class= "container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for @game do |f| %>
<%= f.input :name %>
<%= f.input :label %>
<%= f.input :description %>
<%= f.input :image_link %>
<%= f.input :barcode %>
<%= f.button :submit %>
<%end%>

app/views/shared/_game_show.erb
<div class="card-product">
  <% src = game.image_link ? game.image_link : "https://cf.geekdo-images.com/BZiR636JJdSBwThtH42DVw__opengraph/img/_Iu_09Ab0fvnTJT3gBCfud0LbJg=/0x0:800x420/fit-in/1200x630/filters:strip_icc()/pic3744052.jpg"%>
  <img src=<%= src %>>
  <div class="card-product-infos">
    <h1><%= game.name %></h1>
    <p>
      <%= game.description %>
    </p>
    <%= link_to 'Edit', edit_game_path(game) %>
    <%= button_to('Destroy this game !?', game, :method => :delete) %>
    <%= link_to 'all Games', games_path %>
  </div>
</div>

app/views/shared/_game_show.html.erb
<div class="card-product">
  <% src = game.image_link ? game.image_link : "https://cf.geekdo-images.com/BZiR636JJdSBwThtH42DVw__opengraph/img/_Iu_09Ab0fvnTJT3gBCfud0LbJg=/0x0:800x420/fit-in/1200x630/filters:strip_icc()/pic3744052.jpg"%>
  <img src=<%= src %>>
  <div class="card-product-infos">
    <h1><%= game.name %></h1>
    <p>
      <%= game.description %>
    </p>

    <% if bar&.user == current_user%>
      <%= link_to 'Edit', edit_game_path(game) %>
      <%= button_to('Destroy this game !?', game, :method => :delete) %>
    <%end%>

  </div>
</div>

app/views/shared/_info_window.html.erb
<%= bar.name %>
<%= bar.address %>
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<%= link_to 'View this bar', bar_path(bar)%>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to bars_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    
    <div class="title_navbar">
      <h1>B.A.J</h1>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "#{current_user.first_name}", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://cdn-icons-png.flaticon.com/512/3106/3106773.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "👤 Profil", "#", class: "dropdown-item" %>
              <%= link_to "⚙️ Config", "#", class: "dropdown-item" %>
              <%= link_to "⌽ Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>